name: blitz_gui
description: A GUI for a Raspiblitz node.

version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  convert: any
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  charts_flutter: ^0.9.0
  timeago: ^2.0.26
  pull_to_refresh: ^1.5.8
  passcode_screen: ^1.0.2
  fixnum: ^0.10.11
  protobuf: ^1.0.1
  grpc: ^2.1.3
  flutter_dotenv: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
